CREATE LOCAL TEMPORARY TABLE #PERIOD(
    "NUMBER"    INT, 
    "START"     TIMESTAMP,
    "END"       TIMESTAMP
);

CREATE LOCAL TEMPORARY TABLE #VALS(
    "VALUE"     DECIMAL(32,16),
    "TIMESTAMP" TIMESTAMP,
    "BIN"       INT
);

CREATE LOCAL TEMPORARY TABLE #AVGS(
    "VALUE"     DECIMAL(32,16),
    "TIMESTAMP" TIMESTAMP,
    "BIN"       INT
);
CREATE LOCAL TEMPORARY TABLE #FIN(
    "VALUE"     DECIMAL(32,16),
    "TIMESTAMP" TIMESTAMP,
    "BIN"       INT
);

INSERT INTO #PERIOD SELECT "ELEMENT_NUMBER", "GENERATED_PERIOD_START", 
    "GENERATED_PERIOD_END"  FROM SERIES_GENERATE_TIMESTAMP ('INTERVAL 13 MINUTE','2015-12-24 9:00','2015-12-25 21:30');

INSERT INTO #VALS SELECT DISTINCT "v"."value", "r"."timestamp", 
    SERIES_PERIOD_TO_ELEMENT("r"."timestamp", 'INTERVAL 13 MINUTE','2015-12-24 9:00','2015-12-25 21:30', ROUND_DOWN) FROM 
    "SPET_DIPLOMA"."spet.diploma.data::ctxCore.eValue" AS "v" INNER JOIN
    "SPET_DIPLOMA"."spet.diploma.data::ctxCore.eReading" AS "r" 
    ON "v"."reading" = "r"."id" AND "r"."transport" = '56697BB680504538E10000000A4E731A' INNER JOIN 
    "SPET_DIPLOMA"."spet.diploma.data::ctxCore.eDeviceSensor" AS "d"
    ON "v"."device" = "d"."device" AND "v"."sensor" = "d"."number" INNER JOIN
    "SPET_DIPLOMA"."spet.diploma.data::ctxCore.eSensorType" AS "s"
    ON "d"."sensorType" = "s"."id" AND "s"."measure" = '566D6CFDB5685629E10000000A4E731A'
    WHERE "r"."timestamp" BETWEEN TO_TIMESTAMP('2015-12-24 9:00') AND TO_TIMESTAMP('2015-12-25 21:30');
    
INSERT INTO #AVGS SELECT AVG("VALUE"), ADD_SECONDS(TO_TIMESTAMP('1970-01-01 00:00:00'), 
    AVG(SECONDS_BETWEEN(TO_TIMESTAMP('1970-01-01 00:00:00'), "TIMESTAMP"))), "BIN" FROM #VALS GROUP BY "BIN";

INSERT INTO #FIN SELECT ("NX"."VALUE" + "PR"."VALUE") / 2 AS "VALUE",  ADD_SECONDS("PR"."TIMESTAMP", 
    SECONDS_BETWEEN("PR"."TIMESTAMP", "NX"."TIMESTAMP") / 2) AS "TIMESTAMP", "M"."NUMBER" AS "BIN" FROM ( 
    SELECT * FROM (SELECT "P"."NUMBER", (SELECT MAX("BIN") FROM #VALS WHERE "BIN" < "P"."NUMBER") AS "PREV", 
    (SELECT MIN("BIN") FROM #VALS WHERE "BIN" > "P"."NUMBER") AS "NEXT" FROM 
    (SELECT DISTINCT "NUMBER" FROM #PERIOD EXCEPT SELECT DISTINCT "BIN" FROM #VALS) AS "D"
    INNER JOIN #PERIOD AS "P" ON "D"."NUMBER" = "P"."NUMBER") 
    WHERE (NOT "PREV" IS NULL) AND (NOT "NEXT" IS NULL)
) AS "M" INNER JOIN #AVGS AS "PR" ON "M"."PREV" = "PR"."BIN" 
    INNER JOIN #AVGS AS "NX" ON "M"."NEXT" = "NX"."BIN"
UNION SELECT * FROM #AVGS;

SELECT "C"."VALUE" + SECONDS_BETWEEN("C"."TIMESTAMP", "P"."END") * ("N"."VALUE" - "C"."VALUE") / 
    SECONDS_BETWEEN("C"."TIMESTAMP", "N"."TIMESTAMP") AS "VALUE", "P"."END" AS "TIMESTAMP"
    FROM #FIN AS "C" INNER JOIN #FIN AS "N" ON "C"."BIN" = "N"."BIN" + 1 
    INNER JOIN #PERIOD AS "P" ON "P"."NUMBER" = "C"."BIN" ORDER BY "P"."END";


